-- CountryOfStudy
INSERT INTO country_of_study (name)
VALUES ('Afeganistão'),
       ('África do Sul'),
       ('Albânia'),
       ('Alemanha'),
       ('Andorra'),
       ('Angola'),
       ('Antígua e Barbuda'),
       ('Arábia Saudita'),
       ('Argélia'),
       ('Argentina'),
       ('Armênia'),
       ('Austrália'),
       ('Áustria'),
       ('Azerbaijão'),
       ('Bahamas'),
       ('Bangladesh'),
       ('Barbados'),
       ('Bareine'),
       ('Bélgica'),
       ('Belize'),
       ('Benim'),
       ('Bielorrússia'),
       ('Bolívia'),
       ('Bósnia e Herzegovina'),
       ('Botsuana'),
       ('Brasil'),
       ('Brunei'),
       ('Bulgária'),
       ('Burquina Faso'),
       ('Burundi'),
       ('Butão'),
       ('Cabo Verde'),
       ('Camarões'),
       ('Camboja'),
       ('Canadá'),
       ('Catar'),
       ('Cazaquistão'),
       ('Chade'),
       ('Chile'),
       ('China'),
       ('Chipre'),
       ('Colômbia'),
       ('Comores'),
       ('Congo'),
       ('Coreia do Norte'),
       ('Coreia do Sul'),
       ('Costa do Marfim'),
       ('Costa Rica'),
       ('Croácia'),
       ('Cuba'),
       ('Dinamarca'),
       ('Dominica'),
       ('Egito'),
       ('El Salvador'),
       ('Emirados Árabes Unidos'),
       ('Equador'),
       ('Eritreia'),
       ('Eslováquia'),
       ('Eslovênia'),
       ('Espanha'),
       ('Estados Unidos'),
       ('Estônia'),
       ('Eswatini'),
       ('Etiópia'),
       ('Fiji'),
       ('Filipinas'),
       ('Finlândia'),
       ('França'),
       ('Gabão'),
       ('Gâmbia'),
       ('Gana'),
       ('Geórgia'),
       ('Granada'),
       ('Grécia'),
       ('Guatemala'),
       ('Guiana'),
       ('Guiné'),
       ('Guiné-Bissau'),
       ('Guiné Equatorial'),
       ('Haiti'),
       ('Holanda'),
       ('Honduras'),
       ('Hungria'),
       ('Iémen'),
       ('Ilhas Marshall'),
       ('Ilhas Salomão'),
       ('Índia'),
       ('Indonésia'),
       ('Irã'),
       ('Iraque'),
       ('Irlanda'),
       ('Islândia'),
       ('Israel'),
       ('Itália'),
       ('Jamaica'),
       ('Japão'),
       ('Jordânia'),
       ('Kiribati'),
       ('Kuwait'),
       ('Laos'),
       ('Lesoto'),
       ('Letônia'),
       ('Líbano'),
       ('Libéria'),
       ('Líbia'),
       ('Liechtenstein'),
       ('Lituânia'),
       ('Luxemburgo'),
       ('Macedônia do Norte'),
       ('Madagáscar'),
       ('Malásia'),
       ('Maláui'),
       ('Maldivas'),
       ('Mali'),
       ('Malta'),
       ('Marrocos'),
       ('Maurícia'),
       ('Mauritânia'),
       ('México'),
       ('Mianmar'),
       ('Micronésia'),
       ('Moçambique'),
       ('Moldávia'),
       ('Mônaco'),
       ('Mongólia'),
       ('Montenegro'),
       ('Namíbia'),
       ('Nauru'),
       ('Nepal'),
       ('Nicarágua'),
       ('Níger'),
       ('Nigéria'),
       ('Noruega'),
       ('Nova Zelândia'),
       ('Omã'),
       ('Países Baixos'),
       ('Palau'),
       ('Palestina'),
       ('Panamá'),
       ('Papua-Nova Guiné'),
       ('Paquistão'),
       ('Paraguai'),
       ('Peru'),
       ('Polônia'),
       ('Portugal'),
       ('Quênia'),
       ('Quirguistão'),
       ('Reino Unido'),
       ('República Centro-Africana'),
       ('República Checa'),
       ('República Democrática do Congo'),
       ('República Dominicana'),
       ('Romênia'),
       ('Ruanda'),
       ('Rússia'),
       ('Samoa'),
       ('San Marino'),
       ('Santa Lúcia'),
       ('São Cristóvão e Neves'),
       ('São Tomé e Príncipe'),
       ('São Vicente e Granadinas'),
       ('Senegal'),
       ('Serra Leoa'),
       ('Sérvia'),
       ('Seicheles'),
       ('Singapura'),
       ('Síria'),
       ('Somália'),
       ('Sri Lanka'),
       ('Sudão'),
       ('Sudão do Sul'),
       ('Suécia'),
       ('Suíça'),
       ('Suriname'),
       ('Tailândia'),
       ('Taiwan'),
       ('Tajiquistão'),
       ('Tanzânia'),
       ('Timor-Leste'),
       ('Togo'),
       ('Tonga'),
       ('Trindade e Tobago'),
       ('Tunísia'),
       ('Turcomenistão'),
       ('Turquia'),
       ('Tuvalu'),
       ('Ucrânia'),
       ('Uganda'),
       ('Uruguai'),
       ('Uzbequistão'),
       ('Vanuatu'),
       ('Vaticano'),
       ('Venezuela'),
       ('Vietnã'),
       ('Zâmbia'),
       ('Zimbábue');


-- AreaOfStudy
INSERT INTO area_of_study (name)
VALUES
-- Ciências Exatas e da Computação
('Ciência da Computação'),
('Engenharia de Computação'),
('Engenharia de Software'),
('Tecnologia da Informação'),
('Ciência de Dados'),
('Inteligência Artificial'),
('Cibersegurança'),
('Matemática'),
('Estatística'),
('Física'),
('Química'),

-- Ciências Biológicas e da Terra
('Biologia'),
('Biotecnologia'),
('Ciências Ambientais'),
('Geologia'),
('Astronomia'),

-- Engenharias
('Engenharia Civil'),
('Engenharia Mecânica'),
('Engenharia Elétrica'),
('Engenharia Química'),
('Engenharia Biomédica'),
('Engenharia de Produção'),
('Engenharia de Materiais'),
('Engenharia Aeroespacial'),

-- Arquitetura e Design
('Arquitetura e Urbanismo'),
('Design Gráfico'),
('Design de Moda'),
('Design de Produto'),

-- Ciências Econômicas e Administrativas
('Administração de Empresas'),
('Contabilidade'),
('Finanças'),
('Economia'),
('Marketing'),
('Gestão de Negócios'),
('Empreendedorismo'),

-- Direito e Ciências Sociais
('Direito'),
('Ciência Política'),
('Relações Internacionais'),
('Sociologia'),
('Psicologia'),
('Antropologia'),
('História'),
('Filosofia'),
('Linguística'),

-- Educação e Formação
('Pedagogia'),
('Educação Física'),
('Psicopedagogia'),

-- Saúde e Medicina
('Medicina'),
('Odontologia'),
('Enfermagem'),
('Farmácia'),
('Saúde Pública'),
('Medicina Veterinária'),
('Fisioterapia'),
('Nutrição'),

-- Comunicação, Artes e Humanidades
('Jornalismo'),
('Comunicação Social'),
('Publicidade e Propaganda'),
('Rádio e TV'),
('Música'),
('Belas Artes'),
('Cinema'),
('Teatro'),

-- Hospitalidade e Turismo
('Gestão Hoteleira'),
('Turismo'),

-- Ciências Agrárias
('Agronomia'),
('Ciências Agrícolas'),
('Engenharia Florestal'),

-- Outras Áreas
('Teologia'),
('Estudos Religiosos'),
('Serviço Social'),
('Planejamento Urbano'),
('Estudos de Gênero'),
('Estudos de Desenvolvimento'),
('Ciências Militares');

-- (Add the rest here…)

-- InternationalExam
INSERT INTO international_exam (title)
VALUES ('SAT'),
       ('ACT'),
       ('GRE'),
       ('GMAT'),
       ('LSAT'),
       ('MCAT');
INSERT INTO international_exam (title)
VALUES ('TOEFL'),
       ('IELTS'),
       ('Duolingo English Test'),
       ('Cambridge English C1 Advanced'),
       ('Cambridge English C2 Proficiency'),
       ('PTE Academic'); -- Pearson Test of English
INSERT INTO international_exam (title)
VALUES ('DELF'),
       ('DALF'),
       ('TCF'),
       ('TEF');
INSERT INTO international_exam (title)
VALUES ('TestDaF'),
       ('DSH'),
       ('Goethe-Zertifikat');
INSERT INTO international_exam (title)
VALUES ('DELE'),
       ('SIELE');
INSERT INTO international_exam (title)
VALUES ('HSK'); -- Hanyu Shuiping Kaoshi
INSERT INTO international_exam (title)
VALUES ('International Baccalaureate (IB)'),
       ('A-Levels'),
       ('Advanced Placement (AP)'),
       ('Baccalauréat'),
       ('Abitur'),
       ('Matura');
INSERT INTO international_exam (title)
VALUES ('Cambridge International Examinations (CIE)'),
       ('Edexcel International GCSE'),
       ('International General Certificate of Secondary Education (IGCSE)'),
       ('Cambridge O Level'),
       ('Cambridge A Level'),
       ('Cambridge AS Level'),
       ('Outros Exames Internacionais');

INSERT INTO role (name)
VALUES ('ROLE_ADMIN');
INSERT INTO role (name)
VALUES ('ROLE_MENTOR');
INSERT INTO role (name)
VALUES ('ROLE_MENTEE');